version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeroalpes-hexagonal-architecture-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "5001:5000"
    env_file:
      - .env
    tty: true